# Generated by Django 5.0 on 2026-02-03 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_reports_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='reported_user',
        ),
    ]
