# Generated by Django 5.0 on 2026-02-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_user_report_reported_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reported_user',
            new_name='user',
        ),
    ]
