# Generated by Django 5.0 on 2026-02-03 04:03

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_reported_user_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.CharField(default=django.db.models.fields.Field.__str__, max_length=255),
        ),
    ]
