# Generated by Django 5.0 on 2026-02-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_report_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='comment',
        ),
    ]
