# Generated by Django 5.0 on 2026-02-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_report_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reports',
            field=models.IntegerField(),
        ),
    ]
